name: ppi-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - biopython
  - odfpy
  - pandas
  - matplotlib
  - numpy
  - networkx
  - requests
  - pip
  - pip:
      - pandas-ods-reader
  - cd-hit
